#ifndef KCONIG_H
#define KCONIG_H

#define USE_MINI_UART 0

#define CENTRAL_BLOCK_MEMORY_ALLOCATOR_PRINT_IF_FAILED_ALLOC 
#define CENTRAL_BLOCK_MEMORY_ALLOCATOR_PRINT_IF_FAILED_FREE 

// #define CENTRAL_BLOCK_MEMORY_ALLOCATOR_PRINT_ALLOC_FREE

#define CENTRAL_BLOCK_MEMORY_ALLOCATOR_KERNEL_PANIC_FAILED

#define PAGE_ALLOCATOR_PAGE_SIZE_AS_POWER_OF_TWO 21

#define UART_BASE_CLOCK_FREQUENCY 3000000 // (3 MHz)

#define FRAMEBUFFER_HEIGHT 480
#define FRAMEBUFFER_WIDTH 800

#define MMIO_VIRUTAL_ADDRESS_BASE (void*)0x000080000000
#define FRAMEBUFFER_VIRUTAL_ADDRESS_BASE (void*)0x000100000000

#define CONSOLE_MAX_HEIGHT 440

// #define SD_VERBOSE_LOGGING

#define INTERUPT_END_EVENT_MAX_HANDLERS 4

#endif