#ifndef KConig_H
#define KConig_H

#define USE_MINI_UART 0

#define CENTRAL_BLOCK_MEMORY_ALLOCATOR_UART_PUT_IF_FAILED_ALLOC 
#define CENTRAL_BLOCK_MEMORY_ALLOCATOR_UART_PUT_IF_FAILED_FREE 

#define UART_BASE_CLOCK_FREQUENCY 3000000 // (3 MHz)

#endif